name: login_flutter
description: A flutter login model app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  http: ^0.13.3
  syncfusion_flutter_core: ^23.1.40
  syncfusion_flutter_charts: ^23.1.40
  syncfusion_flutter_gauges: ^23.1.40

  intl: ^0.18.0
  fl_chart: ^0.40.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
